# Generated by Django 4.0 on 2022-11-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
