# Generated by Django 4.0 on 2022-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_second_name_client_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
