# Generated by Django 4.0 on 2022-11-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_visit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(),
        ),
    ]
